### ISSUE TITLE
Support for vector to text 

### ISSUE THREAD

**Issue by Himasnhu-AT** [Anush008/fastembed-rs#100]
Currently fastembed have resource to convert text to vector, rerank text.

But it doesn't support conversion of vectors to text

@Anush008 is it in development plan? Lemme know if I can contribute to it in any way

**Comment by Anush008** [comment]
Not planned really.

**Comment by Himasnhu-AT** [comment]
I think this feature would greatly improve the package. 

I'm new to embedding as a whole, implementing stuff, learned how embeddings are generated and all that.

Lemme know I can help in any way to build this feature

**Comment by Anush008** [comment]
Usually, we don't do vector to text.
But instead store the original text separately for later use.
