### ISSUE TITLE
Are either of gte-multilingual models supported?

### ISSUE THREAD

**Issue by aPaleBlueDot** [Anush008/fastembed-rs#105]
Hi,

Would either of [gte-multilingual-base](https://huggingface.co/Alibaba-NLP/gte-multilingual-base) or [gte-multilingual-mlm-base](https://huggingface.co/Alibaba-NLP/gte-multilingual-mlm-base) work with fastembed-rs ?

Thx!

**Comment by Anush008** [comment]
You can expect them to work, yes.

**Comment by aPaleBlueDot** [comment]
Cool, I'll take them for a test drive soon. Cheers!
