### ISSUE TITLE
Support for colbert-ir/colbertv2.0 embeddings

### ISSUE THREAD

**Issue by Christof23** [Anush008/fastembed-rs#116]
Hi, is there any chance this library can be updated to support `colbert-ir/colbertv2.0` embeddings?

**Comment by Anush008** [comment]
Hey. We'd need a new interface for multi-vectors I think. Not planned as such. Usually new features are added as contributions come by.

**Comment by Christof23** [comment]
Hi @Anush008, thanks for your response. I understand this isn't on the roadmap, however this is supported in the Python client? https://github.com/qdrant/fastembed?tab=readme-ov-file#-sparse-text-embeddings

**Comment by Anush008** [comment]
The is feature disparity between the Rust and Python now.
