### ISSUE TITLE
Build Complexity, Musl Support? - Use of `ort`

### ISSUE THREAD

**Issue by inadahime** [Anush008/fastembed-rs#117]
I'd like to start off with a thank you for developing this library - it's awesome, and so convenient! :)

Cutting to the chase: your implementation of `fastembed` uses `ort` to handle the underlying ONNX inference (*i.e.* the actual *"embed"* in *"fastembed"*). While this allows it to be performant on supported platforms, my understanding is that it leads to a more complex build process and makes targeting `*-musl` (*e.g.* `x86_64-unknown-linux-musl`, my go-to for portable Linux programs) platforms a chore: to do so, you must build the `onnxruntime` library for musl yourself, and then configure the `ort` build to use your local `onnxruntime` with `ORT_LIB_LOCATION=/path/to/musl/onnxruntime/build` during compilation time.

Are there any plans to switch the ONNX inference library to something other than `ort`, like [sonos/tract](https://github.com/sonos/tract.git), or would such a change be better suited to a fork?

**Comment by Anush008** [comment]
Hey @inadahime.
There are no plans as such.

**Comment by inadahime** [comment]
I see.
