### ISSUE TITLE
Requirements with cargo lambda

### ISSUE THREAD

**Issue by gmchaturvedi1** [Anush008/fastembed-rs#119]
While i am trying to build my project in github action . i am facing error of linkage . Do we need any specfic requirement to build 

my cargo.toml is 

`
[package]
name = "chatbot-app-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
arrow-array = "52.2.0"
arrow-schema = "52.2.0"
async-graphql = "7.0.9"
async-graphql-axum = "7.0.9"
aws-config = "1.5.6"
aws-sdk-bedrockruntime = "1.50.0"
aws-sdk-s3 = "1.51.0"
aws-types = "1.3.3"
axum = "0.7.5"
axum-extra = {version="0.9.3",features = ["typed-header"]}
base64 = "0.22.1"
bcrypt = "0.15.1"
bson = { version = "2.12.0", features = ["chrono-0_4"] }

chrono = {version="0.4.38",features = ["serde"]}
dotenv = "0.15.0"
fastembed = "4.0.0"
futures = "0.3.30"
genai = "0.1.9"
jsonwebtoken = "9.3.0"
lambda_http = "0.13.0"
lambda_runtime = "0.13.0"
lancedb = "0.10.0"
lazy_static = "1.5.0"
lettre = "0.11.9"
lopdf = "0.34.0"
mongodb = {version="3.1.0" }
nanoid = "0.4.0"
once_cell = "1.19.0"
openssl = {version = "0.10.66", features = ["vendored"] }
rayon = "1.10.0"
regex = "1.10.6"
ring = "0.17.8"
serde = {version="1.0.210",features = ["derive"]}
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = { version = "1",default-features = false,features = ["macros", "rt-multi-thread"] }
tower-http = {version="0.5.2",features = ["cors"]}
tracing = "0.1.40"
tracing-subscriber = {version="0.3.18",features = [
    "env-filter",
    "fmt",
    "std",
    "json",
] }
ureq ={version= "2.10.1",features = ["charset","json"] }
url = "2.5.2"

[build-dependencies]
cc = {version="1.1.24" }

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-lstdc++",
]

`

my githubaction workflow file as : 

`
---
name: stage
on:
  push:
    branches:
      - stage
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
     
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
        
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
     
          tag: v1.3.0 # Remove this if you want to grab always the latest version
          platform: linux # Other valid options: 'windows' or 'darwin'
          arch: x86_64 # Other valid options for linux: 'aarch64'
      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git

          key: cargo-build-cache-doc-dev
          restore-keys: cargo-build-cache-doc-dev
      - name: Release lambda
        run: |

          cargo lambda build --release
          cargo lambda deploy --binary-name api  api  --enable-function-url

`

**Comment by Anush008** [comment]
> While i am trying to build my project in github action . i am facing error of linkage . Do we need any specfic requirement to build


Not that I know of. 
You could refer to https://docs.rs/ort/latest/ort/, if there are any references.

**Comment by gmchaturvedi1** [comment]
thanks  for quick reply .

**Comment by gmchaturvedi1** [comment]
i am still fixing this but facing a weired issue . sometime fastembed interrupt in between odf download . do we need to do any config for time out.

**Comment by Anush008** [comment]
There's no parameter for that.
