### ISSUE TITLE
support for hugging face sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

### ISSUE THREAD

**Issue by mango009** [Anush008/fastembed-rs#121]
Hi, it seems this model is not supported? Is there a way that we can use this model?

**Comment by Anush008** [comment]
Hey. There's no list for future models.
We usually just add them as contributions come in.

For eg: https://github.com/Anush008/fastembed-rs/pull/92

With the recent refactor, this will include adding the vectors of the model to the tests as well.
