### ISSUE TITLE
Singular test takes too long

### ISSUE THREAD

**Issue by angelofallars** [Anush008/fastembed-rs#13]
The singular test of the library takes around 5 minutes to run, which is too long for a unit test. 

Suggestion: Split the unit test into 7 unit tests for each test in the `models_and_expected_values` vector.

I can code in this change.

**Comment by Anush008** [comment]
When waiting for https://github.com/Anush008/fastembed-rs/actions/runs/7451787665, realized this is awfully long it is.
Yes, splitting them will definitely help.

**Comment by Anush008** [comment]
Removed the larger models from the tests.
