### ISSUE TITLE
Silence ort logging

### ISSUE THREAD

**Issue by ejjonny** [Anush008/fastembed-rs#34]
Hello, is there any way to disable ort logging? Can't see anything useful while embedding calls are running. Thank you!!

**Comment by Anush008** [comment]
I am not sure. Maybe @decahedron1, could help.

**Comment by decahedron1** [comment]
With `tracing-subscriber`, set the `RUST_LOG` environment variable to `ort=warn`.

**Comment by ejjonny** [comment]
Thank you!!
For future readers - you can specify per-crate logging conditions like so
`export RUST_LOG=info,my_crate=info,ort=warn`
(Configuring https://github.com/tokio-rs/tracing)
