### ISSUE TITLE
Question about the removal of BAAI/bge-small-zh-v1.5 model in v3

### ISSUE THREAD

**Issue by AngelLiang** [Anush008/fastembed-rs#35]
Hello,

Firstly, I would like to express my appreciation for your work on the fastembed-rs project. It's been a great tool and has been very helpful in my tasks.

Upon the recent update to version 3, I noticed that the BAAI/bge-small-zh-v1.5 model has been removed. This model has been crucial in my projects and I was wondering why it was removed in the latest version.

Thank you for your time and for the effort you've put into this project. I look forward to your response.

Best regards,
AngelLiang

**Comment by Anush008** [comment]
Hi @AngelLiang. The model source was moved to Hugging face.
If there's a HF source for this model with ONNX, we can add it back.

Here are some example sources
https://huggingface.co/Qdrant/bge-small-en-v1.5-onnx-Q
https://huggingface.co/nomic-ai/nomic-embed-text-v1.

**Comment by Anush008** [comment]
Well, I think I found an Onnx source.

https://huggingface.co/Xenova/bge-small-zh-v1.5/

**Comment by Anush008** [comment]
Yikes. I missed adding it to the README. Will do next time.
