### ISSUE TITLE
support  building for arm architecture.

### ISSUE THREAD

**Issue by Adarsh999bh** [Anush008/fastembed-rs#37]
Hi,
Just wanted to know to what platforms rust fastembed supports.

**Comment by Anush008** [comment]
I am assuming everywhere https://github.com/pykeio/ort builds and https://github.com/microsoft/onnxruntime/releases is available.

**Comment by Adarsh999bh** [comment]
Ok, I'm trying to build sample application mentioned in the README file for aarch64 but I'm facing error linking cc failed exit status: 1
I used below command to build for aarch64
cargo build --target=aarch64-unknown-linux-gnu

**Comment by Anush008** [comment]
Can you try https://github.com/Anush008/fastembed-rs/issues/32#issuecomment-1980615706?

**Comment by Anush008** [comment]
Is this the same as https://github.com/Anush008/fastembed-rs/issues/32?

I see you are trying a cross-platform build. May I recommend https://github.com/cross-rs/cross?

**Comment by Adarsh999bh** [comment]
Sure I'll checkout 
https://github.com/cross-rs/cross

**Comment by Adarsh999bh** [comment]
Fastembed downloads a tarball
https://parcel.pyke.io/v2/delivery/orts/packages/msort-binary/1.17.0/orts-msort_static-v1.17.0-x86_64-unknown-linux-gnu.tgz
The shared library in the tarball is for x86_64 architecture and i believe that while linking that same the process is failing.

**Comment by Adarsh999bh** [comment]
With cross-rs I'm facing similar issue ```error: linking with `aarch64-linux-gnu-gcc` failed: exit status: 1```

**Comment by Adarsh999bh** [comment]
After analysis I have mentioned the exact issue in ring repo 
https://github.com/briansmith/ring/issues/2000
