### ISSUE TITLE
Support fot building on Android 

### ISSUE THREAD

**Issue by harshakhmk** [Anush008/fastembed-rs#39]
Hi, I am trying to build fastembed for Android through cross compilation
But I am getting error: 
```
Error fail to run custom build comment for ort-sys v2. 0.0-rc.0
```
Just wanted to know if fastembed is supported for Android
Command used for cross compilation
```
cargo-ndk --target aarch64-linux-android --platform 21 -- build

**Comment by Anush008** [comment]
I don't think `ort` supports building for Android.

**Comment by harshakhmk** [comment]
Confirmed with the ort community, "Android is supported but needed to build onnxruntime from source " is what they said
Just wanted to confirm the support of fastembed for Android

**Comment by Anush008** [comment]
If you can build FastEmbed for Android it should work then.
