### ISSUE TITLE
How to load a local embedding model. 

### ISSUE THREAD

**Issue by RWayne93** [Anush008/fastembed-rs#42]
I don’t see in the documentation how I can instantiate an embedding model from my local file system give the file path to the downloaded embedding model. 

 I’m assuming this reaches out to hunggingface and stores the embedding model in local cache somewhere.

**Comment by Anush008** [comment]
#40 should resolve this.

**Comment by Anush008** [comment]
Currently, the specified model is downloaded and cached locally.
With #40, you should be able to use any local model files.

**Comment by RWayne93** [comment]
Thanks for the fast reply. I see other sentence transformer models on the supported list so if I wanted to bring my own model like all-mpnet-base-v2 when it’s merged without issues?

**Comment by Anush008** [comment]
You could also do a PR to add the model to the library.

For example: https://github.com/Anush008/fastembed-rs/pull/36

**Comment by Anush008** [comment]
Resolved with https://github.com/Anush008/fastembed-rs/releases/tag/v3.3.0.
