### ISSUE TITLE
[issue] Fastembed build is failing 

### ISSUE THREAD

**Issue by jay11ca39** [Anush008/fastembed-rs#43]
I have created a sample cargo project:
$ cargo init 

Added Fastembed dependency in cargo.toml file .. 
[dependencies]
fastembed  = "3"

$ cargo build 

It is failing .. 

As per the analysis it is due to yesterday's release of ort.. in which apis got changed..

**Comment by Anush008** [comment]
Shouldn't be the case. Since the `ort` version is pinned in FastEmbed and we have not bumped it.

**Comment by Anush008** [comment]
You're right. I'll add fix.

**Comment by jay11ca39** [comment]
> Shouldn't be the case. Since the `ort` version is pinned in FastEmbed and we have not bumped it.

Thanks @Anush008 for reply. 
But I was able to build it earlier.. there is no changes in my side. Creating a sample project also not building . 
Did you build it today or can you just try to create a sample cargo project and add fastembed dependency.. ?

**Comment by Anush008** [comment]
Yes. My bad. I reran the CI of #40. It failed.

**Comment by Anush008** [comment]
Thanks for reporting Jay.

**Comment by jay11ca39** [comment]
> Thanks for reporting Jay.

You are welcome..

> Yes. My bad. I reran the CI of #40. It failed.

I am able to build with fix which is merged  #44

**Comment by Anush008** [comment]
FastEmbed v3.3.0 should work fine.
