### ISSUE TITLE
Bump ort to latest

### ISSUE THREAD

**Issue by Anush008** [Anush008/fastembed-rs#46]
### Description

The latest release of https://github.com/pykeio/ort has improvements and some breaking changes in the usage.

We are currently pinned to a previous version.

### Task

Update ort to latest with required usage changes.

**Comment by joshua-mo-143** [comment]
I'd be happy to do this since v2.0.0-rc.2 is actually quite important and allows usage of ort with web servers (via `run_async`).

**Comment by Anush008** [comment]
Hi, @joshua-mo-143. It will be a much-appreciated contribution.
