### ISSUE TITLE
Add support for mixedbread-ai/mxbai-embed-large-v1

### ISSUE THREAD

**Issue by prabirshrestha** [Anush008/fastembed-rs#47]
Add support for https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1.

https://www.mixedbread.ai/blog/mxbai-embed-large-v1

**Comment by Anush008** [comment]
Hi Prabir. Thanks for raising the issue.


I am deep into work this week. If anyone is interested in a contribution, a PR could look like

https://github.com/Anush008/fastembed-rs/pull/36

Plus, any optional modification this model might need.
