### ISSUE TITLE
passage_embed() has been removed. Is it recommended to prepend ourselves before embedding?

### ISSUE THREAD

**Issue by SimonCW** [Anush008/fastembed-rs#50]
Hi @Anush008,
I've seen that the `passage_embed()` and `query_embed()` methods have been removed in this PR https://github.com/Anush008/fastembed-rs/pull/25. Is there a reason for this? It is recommended to prepend "passage:" and "query:" ourselves?

**Comment by Anush008** [comment]
Hi Simon.

Since prefixes like these are specific to the models, it makes sense for users to attach those themselves.

**Comment by SimonCW** [comment]
Ok, got you! Thanks for the quick reply! For others new to this: You'll see whether the models expects the passage and query parameters on the huggingface model card, e.g. https://huggingface.co/intfloat/multilingual-e5-small
