### ISSUE TITLE
Request for Examples, Documentation Illustrating use with other libraries

### ISSUE THREAD

**Issue by gwpl** [Anush008/fastembed-rs#61]
Could you please consider adding examples to your repository?

Also examples showing how to use your crate and e.g. 

* [ ] calculate distances between vectors (here is some inspiration in python: https://gist.github.com/gwpl/4f6c2aa1401febbf0873859495496315 ) 

Or show how to use with other rust AI libraries, vector dbs or math libraries, to compute different kinds of distances, similarities ( [[Dot product: Dot]](https://en.wikipedia.org/wiki/Dot_product), [[Cosine similarity: Cosine]](https://en.wikipedia.org/wiki/Cosine_similarity), [[Euclidean distance: Euclid]](https://en.wikipedia.org/wiki/Euclidean_distance), [[Manhattan distance: Manhattan]](https://en.wikipedia.org/wiki/Taxicab_geometry) ).

Ideal would be tiny [[[example programs in `examples` directory]](https://doc.rust-lang.org/cargo/guide/project-layout.html) that could be run with cargo.

**Comment by gwpl** [comment]
* [ ]  https://crates.io/crates/chromadb-rs 
* [ ] https://github.com/m1guelpf/tinyvector 
* [ ] https://github.com/instant-labs/instant-distance

**Comment by Anush008** [comment]
Hi @gwpl. Thanks for raising the issue.
I usually work in the library during weekends. I can take a look then.
In the meantime, contributions are welcome.

**Comment by Anush008** [comment]
I am thinking the library's interface is simple and docs.rs/README should be sufficient.
