### ISSUE TITLE
Cloning of Input Documents

### ISSUE THREAD

**Issue by smelm** [Anush008/fastembed-rs#65]
First of, thanks for the great work.

I am wondering why the API of `embed` takes ownership of the texts vector instead of borrowing it. I tried it locally and it works just as well with a reference which removes the need of cloning as well.

https://github.com/Anush008/fastembed-rs/blob/044f3eb0d7e91f56b31b79dc714b4fb67fa58684/src/text_embedding.rs#L225

**Comment by Anush008** [comment]
Hi @smelm. Thanks for raising this issue.
Unfortunately, switching now will be a breaking change.
