### ISSUE TITLE
Dependency versions too rigid

### ISSUE THREAD

**Issue by joshua-mo-143** [Anush008/fastembed-rs#66]
It seems that in order to use this crate, we need exactly the same versions of the dependencies that this crate already has. 

Is there any chance we can have this loosened? It would be great to not have to keep checking what version this library uses every time I (or anyone else) want(s) to use a dependency that is owned by it. This is mostly relevant when referring to `serde-json` and many other libraries that have mostly already stabilised - for example, `serde-json`'s changelog: https://github.com/serde-rs/json/releases.

Otherwise, great crate! Looking forward to using this a lot more in the future so I don't have to use Candle or a similar framework for absolutely everything :sweat:

**Comment by Anush008** [comment]
Hey @joshua-mo-143. Great suggestion. Will look into this.
