### ISSUE TITLE
sentence-transformers/clip-ViT-B-32-multilingual-v1 model

### ISSUE THREAD

**Issue by yaman** [Anush008/fastembed-rs#7]
I was working on exporting sentence-transformers/clip-ViT-B-32-multilingual-v1 model to onnx without success. Finally I figured out by manipulating model with torch.onnx. I can contribute onnx model to fastembed-rs with the custom steps of torch.onnx export(python script).

Should I create a pull request?

**Comment by Anush008** [comment]
Hey @yaman.
This library intends to maintain parity with the original Python implementation.
I recommend model contributions should be made to https://github.com/qdrant/fastembed.

Any new changes there should be reflected here soon.

**Comment by yaman** [comment]
Thanks @Anush008 for the response. I created an issue at https://github.com/qdrant/fastembed/issues/70
