### ISSUE TITLE
Optional openssl

### ISSUE THREAD

**Issue by joshniemela** [Anush008/fastembed-rs#70]
OpenSSL can often be annoying to use as a build dependency and it should be possible to use the `rustls` package to replace `openssl`

**Comment by Anush008** [comment]
We don't have it as a direct dependency though.
Could you please elaborate?

**Comment by joshniemela** [comment]
If your system doesn't have OpenSSL installed, `cargo build` will throw an error.
This most likely is happening due to `hf-hub` or some other dependency that downloads stuff, I was not able to find the cause whilst swiftly looking through the dependencies

**Comment by Anush008** [comment]
This would need a fix in the upstream projects then.

**Comment by mcmah309** [comment]
It is being pulled in by `fastembed` -> `hf-hub` -> `native-tls` -> `openssl`

**Comment by Anush008** [comment]
Closing since stale. Please feel free to re-open if needed.
