### ISSUE TITLE
Small reranking models

### ISSUE THREAD

**Issue by jawj** [Anush008/fastembed-rs#75]
@Anush008 and @GrisaiaEvy, many thanks for your work on this library.

At present, multiple embedding/bi-encoding models are supported plus the user can bring their own. But for reranking/cross-encoding, only `bge-reranker-base` is available.

I'd like to use a smaller reranking model, ideally sized on par with the default embedding model, `bge-small-en-v1.5` (something like [`jina-reranker-v1-turbo-en`](https://huggingface.co/jinaai/jina-reranker-v1-turbo-en) seems promising).

How hard do you think it would be to add support for a small reranking model like this, or for bring-your-own reranking models? Is it on your roadmap?

**Comment by Anush008** [comment]
Hey @jawj. There's no roadmap as such. Everyone just makes up their mind their and does some contributions(Me included). Almost all new propositions are accepted.

**Comment by jawj** [comment]
Thanks for the quick reply.

OK. I guess my two follow-ups are:

* Is it something you'd be interested in adding?
* Alternatively, how big and how tricky a job do you think it would be for me to add? I have some programming experience, but I'm fairly new both to Rust and to this area.

**Comment by Anush008** [comment]
Adding a new reranker model shouldn't be much work.
Just listing it at https://github.com/Anush008/fastembed-rs/blob/ac715a5ad1d4f7483dd86e976e83b2e101505ad2/src/models/reranking.rs#L2-L15 should do if I it's the same architecture.

**Comment by Anush008** [comment]
An example of a dense model addition is https://github.com/Anush008/fastembed-rs/pull/69

**Comment by jawj** [comment]
Great — I think I'll have a go at this, then.
