### ISSUE TITLE
fastembed 3 panic on Windows 11: Failed to retrieve onnx/model.onnx

### ISSUE THREAD

**Issue by zhaoyii** [Anush008/fastembed-rs#78]
The program panics while attempting to load the `onnx/model.onnx model`，When running `fastembed 3` on Windows 11 with Rust 1.78.0.

```
thread 'main' panicked at \fastembed-3.9.0\src\text_embedding.rs:130:33:
Failed to retrieve onnx/model.onnx
```

Whereas it runs smoothly with `fastembed 2`.

**Comment by Anush008** [comment]
Can you try clearing the `.fastembed_cache` directory?

**Comment by zhaoyii** [comment]
The `.fastembed_cache` directory was not found. Due to some network issues, direct access to `hugginface.co` is not possible. The version of `ureq` relied upon by `hf-hub` does not support configuring proxy parameters such as `HTTPS_PROXY` through environment variables, preventing the download of models.

Could you please instruct me on how to manually download the model to the cache folder? I attempted this, but it might not be in the correct format, leading to a failure to run.

**Comment by Anush008** [comment]
You can just download the model repo from the HuggingFace site and set the value for the `cache_dir` path when initializing `TextEmbedding`.

**Comment by zhaoyii** [comment]
Thank you for your answer. [hf-hub](https://github.com/huggingface/hf-hub) seems to be not very user-friendly. I solved the problem by using the [huggingface_hub ](https://github.com/huggingface/huggingface_hub) library in Python to download the model.

**Comment by holmofy** [comment]
@zhaoyii How can I use the files downloaded by huggingface_hub in fastembed?

**Comment by holmofy** [comment]
@Anush008 hf-hub already supports the HF_ENDPOINT environment variable:

* https://github.com/huggingface/hf-hub/commit/ac22200ea0b5af4d8c362f699be0340647b19060

**Comment by Anush008** [comment]
Hey @holmofy. We'll have to wait for `hf-hub` to make a new release.
