### ISSUE TITLE
Example of specifying an ExecutionProvider?

### ISSUE THREAD

**Issue by jawj** [Anush008/fastembed-rs#80]
Is it possible to add to the docs an example of specifying one or more execution providers (e.g. CUDA or CoreML) when creating a model? I can't seem to figure out how to make that work.

**Comment by Anush008** [comment]
I don't have GPU access. So haven't done so myself.

**Comment by Anush008** [comment]
If someone can contribute please do.
I am closing this issue since it is stale.

**Comment by lmmx** [comment]
- @jzombie did this in #178 and left some notes there, I was curious about the same
- Duplicate issue in #8
