### ISSUE TITLE
How to change the dimensionality for nomic-ai/nomic-embed-text-v1.5 ?

### ISSUE THREAD

**Issue by cgisky1980** [Anush008/fastembed-rs#83]
nomic-embed-text-v1.5 is an improvement upon [Nomic Embed](https://huggingface.co/nomic-ai/nomic-embed-text-v1) that utilizes [Matryoshka Representation Learning](https://arxiv.org/abs/2205.13147) which gives developers the flexibility to trade off the embedding size for a negligible reduction in performance.

```
from nomic import embed

output = embed.text(
    texts=['Nomic Embedding API', '#keepAIOpen'],
    model='nomic-embed-text-v1.5',
    task_type='search_document',
    dimensionality=256,
)

print(output)

```

**Comment by Anush008** [comment]
Not supported yet.
