### ISSUE TITLE
Support users supplying their own HF model cards

### ISSUE THREAD

**Issue by spikecodes** [Anush008/fastembed-rs#93]
I know users can currently provide onnx files but what would be useful, instead of simply hardcoding the model list, is allowing users to add models based on a hugging face repo ID and other model info.

This would avoid having to rewrite the infrastructure to download and cache an onnx file from the huggingface repo based on a HF repo ID.

Something like this:

```rs
TextEmbedding::try_new_from_model_info(ModelInfo)
```

where use can supply a `ModelInfo` (which is already a pub struct):
```
pub struct ModelInfo {
    pub model: EmbeddingModel,
    pub dim: usize,
    pub description: String,
    pub model_code: String,
    pub model_file: String,
}
```

**Comment by Anush008** [comment]
The problem I see is, people would expect this to work with every model on HF and raise issues if it doesn't.

Right now, we're able to curate the models by adding them manually and testing.

**Comment by spikecodes** [comment]
That makes sense, though wouldn't that be equally an issue with users currently loading their own onnx files? I imagined this just being an abstraction on that to make it easier to fetch models' onnx files from HF.
