### ISSUE TITLE
Load Tokenizer

### ISSUE THREAD

**Issue by lywa1998** [Anush008/fastembed-rs#97]
I reviewed the common module and found some unnecessary implementations.  
1. In the file, Tokenizer has been renamed to TokenizerImpl. The tokenizers crate implements the From<TokenizerImpl> trait for Tokenizer.
2. It seems that `load_tokenizer_hf_hub` function uses multiple configuration files to load the Tokenizer. However, tokenizer.json already includes all the configurations for the trained tokenizers. I tested using `Tokenizer::from_file("tokenizer.json")` directly, and the result was the same as that of `load_tokenizer_hf_hub`.

**Comment by Anush008** [comment]
Thanks for the info @lywa1998.
